import { Result } from "better-result";

import { desktopWebFrontends, type ProjectConfig } from "../../types";
import { addPackageDependency } from "../../utils/add-package-deps";
import { AddonSetupError, UserCancelledError } from "../../utils/errors";
import { runOptionalStep } from "../../utils/optional-step";
import { setupEvlog } from "./evlog-setup";
import { setupFumadocs } from "./fumadocs-setup";
import { setupMcp } from "./mcp-setup";
import { setupOxlint } from "./oxlint-setup";
import { setupSkills } from "./skills-setup";
import { setupTauri } from "./tauri-setup";
import { setupTui } from "./tui-setup";

const runSetup = <T>(setupFn: () => Promise<Result<T, AddonSetupError | UserCancelledError>>) =>
  runOptionalStep(setupFn, "Addon setup cancelled.");

export async function setupAddons(config: ProjectConfig): Promise<void> {
  const { addons, frontend, projectDir } = config;
  const hasWebFrontend = frontend.some((value) =>
    (desktopWebFrontends as readonly string[]).includes(value),
  );

  if (addons.includes("tauri") && hasWebFrontend) {
    await runSetup(() => setupTauri(config));
  }

  if (addons.includes("oxlint")) {
    await runSetup(() => setupOxlint(projectDir, config.packageManager));
  }

  if (addons.includes("lefthook")) {
    await runSetup(async () => {
      await setupLefthook(projectDir);
      return Result.ok(undefined);
    });
  }

  if (addons.includes("fumadocs")) {
    await runSetup(() => setupFumadocs(config));
  }

  if (addons.includes("opentui")) {
    await runSetup(() => setupTui(config));
  }

  if (addons.includes("skills")) {
    await runSetup(() => setupSkills(config));
  }

  if (addons.includes("mcp")) {
    await runSetup(() => setupMcp(config));
  }

  if (addons.includes("evlog") || addons.includes("axiom")) {
    await runSetup(() => setupEvlog(config));
  }
}

export async function setupLefthook(projectDir: string) {
  await addPackageDependency({
    devDependencies: ["lefthook"],
    projectDir,
  });
  // lefthook.yml is generated by template-generator from templates/addons/lefthook/
}
